# load packages

import pandas as pd
import os
from snakemake.utils import validate
from snakemake.utils import min_version

min_version("9.5.1")

# configuration
configfile: "../config/config.yaml"

#validate(config, "../config/config.schema.yaml")

# container version of workflow
#containerized: "docker://milesroberts/poolseq-kmers"


# load samples
reads = pd.read_table(
    "../config/samples.tsv", sep="\t", dtype={"Run": str}
).set_index(["Run"], drop=False)

#validate(parameters, "../config/parameters.schema.yaml")

# Define rules too fast to bother with cluster submission
localrules: all, batch_per_sample

#rule all:
#    input:
#        expand("samtools_stats/{ID}_{species}_{linref}.txt", ID = reads["BioSample"], linref = config["linrefs"]),
#        expand("bcftools_stats_results/{species}_{linref}.txt", linref = config["linrefs"]),
#        expand("mk_test_{species}_{linref}/mk.tsv", linref = config["linrefs"]),
#        expand("salmon_quantmerge_results/{species}_{linref}.txt", linref = config["linrefs"]),
#        expand("pixy_results/{linref}_{stat}.txt", linref = config["linrefs"], stat = ["pi", "watterson_theta", "tajima_d", "dxy", "fst"]),
#        expand("kmer_distances_{species}.txt", species = reads["Species"].unique()),
#        "multiqc_report.html"

rule kmers_only:
    input:
     expand("kmer_distances_{species}.txt", species = reads["Species"].unique())

rule batch_per_sample:
    input:
        expand("bcftools_linref_results/{ID}_{ref}_{split}.vcf.gz", ID = reads["BioSample"], ref = config["linrefs"], split = range(10, 10 + config["splits"])),
        expand("cbf_results/{ID}.txt", ID = reads["BioSample"]),
        expand("salmon_quant_results/{ref}_{rna}/quant.sf", ref = config["linrefs"], rna = config["rna"])

## Jules branch
include: "rules/jules.smk"

## Data download and QC rules
include: "rules/data_download.smk"
include: "rules/fastp.smk"
include: "rules/multiqc.smk"
include: "rules/change_headers.smk"

## Linear alignment rules
include: "rules/bwa.smk"

## SAM tools rules
include: "rules/samtools.smk"

## K-mer counting rules
include: "rules/kmc.smk"
include: "rules/cbf.smk"

## Pangenome graph building and alignment rules
include: "rules/pggb.smk"
include: "rules/vg.smk"

## Gene expression quantification
include: "rules/salmon.smk"

## Population genetics summary rules
include: "rules/degenotate.smk"
include: "rules/pixy.smk"

## Split sites
include: "rules/split.smk"

## Mash k-mer distances
include: "rules/mash.smk"
