# load packages

import pandas as pd
import os
import glob
from snakemake.utils import min_version

min_version("9.5.1")

# configuration
configfile: "../config/config.yaml"

# load samples
reads = pd.read_table(
    "../config/samples_medium.tsv", sep="\t", dtype={"Run": str}
).set_index(["Run"], drop=False)

# auto-detect linear references from the genomes provided in config/linear_genomes/sequence/
#linrefs = [os.path.splitext(os.path.basename(f))[0]
#           for f in glob.glob("../config/linear_genomes/sequence/*.fa")]

# Define rules too fast to bother with cluster submission
localrules: all, batch_per_sample

#rule all:
#    input:
#        expand("results/samtools_stats/{ID}_{ref}.txt", ID = reads["BioSample"].unique(), ref = linrefs),
#        expand("results/bcftools_stats/{ref}.txt", ref = linrefs),
#        expand("results/mk_test_{ref}/mk.tsv", ref = linrefs),
#        expand("results/salmon_quantmerge/{ref}.txt", ref = linrefs),
#        expand("results/pixy/{ref}_{stat}.txt", ref = linrefs, stat = ["pi", "watterson_theta", "tajima_d", "dxy", "fst"]),
#        expand("results/kmer_distances_{species}.txt", species = reads["Species"].unique()),
#        "results/multiqc/multiqc_report.html"

rule jules_only:
    input:
        expand("results/psmc/{srr}.psmc", srr = reads["Run"]),
        expand("results/roh/{srr}_ROH.txt", srr = reads["Run"])

rule kmers_only:
    input:
     #expand("results/kmer_distances_{species}.txt", species = reads["Species"].unique()),
     expand("results/batch_tracker/{species}.done", species = reads["Species"].unique())

rule batch_per_species:
    input:
        "results/kmer_distances_{species}.txt",
        "results/paste/{species}.txt.gz",
        "results/kmc_histo/{species}.txt",
        expand("results/fastp/post_trim/{ID}.json", ID=lookup(query="Species == '{species}'", within=reads, cols="Run")),
        expand("results/fastp/post_rm_contam/{ID}.json", ID=lookup(query="Species == '{species}'", within=reads, cols="BioSample"))
    output:
        touch("results/batch_tracker/{species}.done")

#rule batch_per_sample:
#    input:
#        expand("results/bcftools_linref/{ID}_{ref}_{split}.vcf.gz", ID = reads["BioSample"].unique(), ref = linrefs, split = range(10, 10 + config["splits"])),
#        expand("results/cbf/{ID}.txt", ID = reads["BioSample"].unique()),
#        expand("results/salmon_quant/{ref}_{rna}/quant.sf", ref = linrefs, rna = reads[reads["LibraryType"] == "rna"]["Run"].tolist())

## Jules branch
include: "rules/jules.smk"

## Data download and QC rules
include: "rules/data_download.smk"
include: "rules/fastp.smk"
#include: "rules/multiqc.smk"
#include: "rules/change_headers.smk"

## Linear alignment rules
#include: "rules/bwa.smk"

## SAM tools rules
#include: "rules/samtools.smk"

## K-mer counting rules
include: "rules/kmc.smk"
include: "rules/cbf.smk"

## Pangenome graph building and alignment rules
#include: "rules/pggb.smk"
#include: "rules/vg.smk"

## Gene expression quantification
#include: "rules/salmon.smk"

## Population genetics summary rules
#include: "rules/degenotate.smk"
#include: "rules/pixy.smk"

## Split sites
#include: "rules/split.smk"

## Mash k-mer distances
#include: "rules/mash.smk"
