# List of chromosome names, for parallelization =========================
chroms:
 - "Chr1"
 - "Chr2"
 - "Chr3"
 - "Chr4"
 - "Chr5"

# kmc parameters ====================================================

## k-mer length
k: 31

## minimum k-mer count for kmc3
mincount: 1

## maximum k-mer count for kmc3
maxcount: 100000

## size of counting bloom filter array
array_size: 100000

## number of hash functions
num_hash: 4

# fastp parameters ===================================================

## unqualified_percent_limit for fastp: how many percents of bases are allowed to be unqualified in terms of quality score
unqualLimit: 40

## quality score for read trimming
qualThresh: 30

## window length for read trimming
windowLength: 1

# samples to download from SRA =======================================
# arabiodpsis thaliana: 
samples:
 - "SRR1946569"
 - "SRR1946568"

# arabidopsis lyrata: https://doi.org/10.1093/molbev/msx193
outgroup:
 - "SRR5124999"
 - "SRR5124997"

# arabiodpsis thaliana:
rna:
 - "ERR1589014"
 - "ERR1589013"
 - "ERR1589012"

# contaminants to include in read QC =================================

## contaminants to download from ncbi
ncbi_contams:
 - "human"
 - "eubacteria"
 - "fungi"
 - "archaea"
 - "viruses"

## custom contaminants, user provides fasta file
custom_contams:
 - "arabiodpsis_thaliana_chrc_chrm"

# references =========================================================

## linear reference genome to align samples to

#linrefs:
# - "x"
# - "y"

linrefs:
 - "ah7"
 - "arb0"
 - "belmonte494"
# - "bor1"
# - "cdm0"
# - "col"
# - "dra2"
# - "elk1"
# - "etna2"
# - "got22"
# - "hs0"
# - "kelsterbach2"
# - "ket10"
# - "kondara"
# - "kz9"
# - "liof095"
# - "ll0"
# - "mammo1"
# - "meh0"
# - "ms0"
# - "nz1"
# - "per1"
# - "pra6"
# - "pu223"
# - "sha"
# - "sij1"
# - "sij2"
# - "sorbo"
# - "st0"
# - "tibet"
# - "tusb303"
# - "yilong"

## pangenomes to align samples to
#panrefs:
# - "z"
 
panrefs:
 - "panFS"
