#
psmc_path: "~/temp/whatever.py"

adapter_path: "../config/trimmomatic_adapters.fa"

q: 20

Q: 20

G: 30

AFdflt: 0.4

#
reference_genome_path: "../config/jules_ref_genomes/"

# Split sites for genotype calling into N lists for parallelization =========================

splits: 40

# kmc parameters ============================================================================

## k-mer length
k: 31

## minimum k-mer count for kmc3
mincount: 5

## maximum k-mer count for kmc3
maxcount: 100000

## size of counting bloom filter array
array_size: 500000

## number of hash functions
num_hash: 4

## number of k-mer hits that a read needs to have to determine contamination
contam_match_limit_count: 2

# fastp parameters ==========================================================================

## unqualified_percent_limit for fastp: how many percents of bases are allowed to be unqualified in terms of quality score
unqualLimit: 40

## quality score for read trimming
qualThresh: 30

## window length for read trimming
windowLength: 1

## maximum number of N bases allowed per read
nBaseLimit: 5

# contaminants to include in read QC =========================================================

## contaminants to download from ncbi
ncbi_contams:
 - "human"

## custom contaminants, user provides fasta file
custom_contams:
