$schema: "https://json-schema.org/draft/2020-12/schema"
description: universal parameters applied to all samples
properties:
  splits:
    description: Number of genome partitions to process in parallel, does not have to be same as number of chromosomes
    type: integer
    default: 32
    maximum: 90
    minimum: 1
  k:
    description: k-mer length/minimum read trim length
    type: integer
    default: 31
  array_size:
    description: size of counting bloom filter array
    type: integer
    default: 100000
    minimum: 1000
  num_hash:
    description: number of hash functions for bloom filter array
    type: integer
    default: 4
    minimum: 1
  contam_match_limit:
    description: number of k-mer hits that a read needs to have to determine contamination
    type: number
    default: 0.8
    minimum: 0.01
    maximum: 1
  mincount:
    description: minimum k-mer count threshold and minimum read depth
    type: integer
    default: 5
  maxcount:
    description: maximum k-mer count
    type: integer
    default: 10000
  unqualLimit:
    description: the unqualified_percent_limit for fastp, how many percents of bases are allowed to be unqualified in terms of quality score
    type: integer
    default: 40
  windowLength:
    description: window length for read trimming
    type: integer
    default: 1
  nBaseLimit:
    description: max number of N bases allowed in fastq read
    type: integer
    default: 5
  samples:
    description: list of SRA accession numbers for DNA-seq within the in-group species
    type: array
    items:
      type: string
  outgroup:
    description: list of SRA accession numbers for DNA-seq within an out-group species
    type: array
    items:
      type: string
  rna:
    description: list of SRA accession numbers for RNA-seq within an in-group species
    type: array
    items:
      type: string
  ncbi_contams:
    description: list of NCBI taxon ids for species to consider as contaminants
    type: array
    items:
      type: string
  custom_contams:
    description: list of fasta files to also consider as contaminants, useful if contaminants are not present as ncbi reference genome
    type: array
    items:
      type: string
  linrefs:
    description: prefixes of fasta files that are linear reference genomes of the in-group species
    type: array
    items:
      type: string
