# k-mer length
k: 16

# unqualified_percent_limit for fastp: how many percents of bases are allowed to be unqualified in terms of quality score
unqualLimit: 40

# quality score for read trimming
qualThresh: 30

# window length for read trimming
windowLength: 1

# samples to download from SRA
samples:
 - "SR1234567"
 - "SR7676756"

# contaminants to include in read QC
contams:
 - "human"

# linear reference genome to align samples to
linrefs:
 - "x"
 - "y"

# pangenomes to align samples to
panrefs:
 - "x"
