executor: slurm
jobs: 100
cores: 100000

# rules to execute locally, because they're too fast to bother with cluster submission
# localrules: all_one_pops, all_two_pops, all

# use sensible defaults for your cluster
default-resources:
    slurm_account: "co_moilab"
    slurm_partition: "savio3_htc"
    slurm_qos: "savio_lowprio"
    #slurm_partition: "savio4_htc"
    #slurm_qos: "moilab_htc4_normal"
    ntasks: 1
    cpus_per_task: 1
    runtime: "30m"
    mem_mb: 0

# here only rules, which require different (more) resources:
set-resources:
    sra:
        cpus_per_task: 4
        runtime: "240m"
    biosample:
        runtime: "20m"
    fastp:
        runtime: "int(min(max(3*input.size_mb/(1024*threads), 10), 1440))"
        cpus_per_task: 8
    qc_post_rm_contam:
        runtime: "int(min(max(3*input.size_mb/(1024*threads), 10), 1440))"
        cpus_per_task: 8
    kmc_ref_db:
        runtime: "30m"
        cpus_per_task: 4
    kmc_rm_contam:
        runtime: "int(min(max(5*input.size_mb/1024, 10), 1440))"
        cpus_per_task: 8
    kmc: 
        runtime: "int(min(max(4*input.size_mb/(1024*threads), 10), 1440))"
        cpus_per_task: 8
    kmc_combine_dbs:
        runtime: "120m"
        cpus_per_task: 8
    prejoin:
        slurm_partition: "savio4_htc"
        slurm_qos: "moilab_htc4_normal"
        runtime: "300m"
    paste:
        runtime: "int(min(max(input.size_mb/(1024*5), 10), 1440))"
    pigz:
        cpus_per_task: 8
        runtime: "int(min(max(4*input.size_mb/(1024*threads), 10), 1440))"
    counting_bloom_filter:
        runtime: "int(min(max(3*input.size_mb*60/(30*1024), 10), 1440))"
        cpus_per_task: 1
    jules_psmc_subset_bam:
        runtime: "180m"
        cpus_per_task: 8

# parallelization with threads needs to be defined separately:
# threads and cpus_per_task are supposed to be synonymous for this plugin, but for some reason I need to specify them separately
set-threads:
    sra: 4
    fastp: 8
    qc_post_rm_contam: 8
    kmc: 8
    kmc_combine_dbs: 8
    kmc_ref_db: 4
    kmc_rm_contam: 8
    pigz: 8
    jules_psmc_subset_bam: 8
